/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YorumlarRouteImport } from './routes/yorumlar'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as FizyoterapistRouteImport } from './routes/fizyoterapist'
import { Route as EgitmenlerimizRouteImport } from './routes/egitmenlerimiz'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const YorumlarRoute = YorumlarRouteImport.update({
  id: '/yorumlar',
  path: '/yorumlar',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const FizyoterapistRoute = FizyoterapistRouteImport.update({
  id: '/fizyoterapist',
  path: '/fizyoterapist',
  getParentRoute: () => rootRouteImport,
} as any)
const EgitmenlerimizRoute = EgitmenlerimizRouteImport.update({
  id: '/egitmenlerimiz',
  path: '/egitmenlerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/egitmenlerimiz': typeof EgitmenlerimizRoute
  '/fizyoterapist': typeof FizyoterapistRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/yorumlar': typeof YorumlarRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/egitmenlerimiz': typeof EgitmenlerimizRoute
  '/fizyoterapist': typeof FizyoterapistRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/yorumlar': typeof YorumlarRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/egitmenlerimiz': typeof EgitmenlerimizRoute
  '/fizyoterapist': typeof FizyoterapistRoute
  '/galeri': typeof GaleriRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/yorumlar': typeof YorumlarRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/egitmenlerimiz'
    | '/fizyoterapist'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/yorumlar'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/egitmenlerimiz'
    | '/fizyoterapist'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/yorumlar'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/egitmenlerimiz'
    | '/fizyoterapist'
    | '/galeri'
    | '/hakkimizda'
    | '/iletisim'
    | '/yorumlar'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  EgitmenlerimizRoute: typeof EgitmenlerimizRoute
  FizyoterapistRoute: typeof FizyoterapistRoute
  GaleriRoute: typeof GaleriRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  YorumlarRoute: typeof YorumlarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/yorumlar': {
      id: '/yorumlar'
      path: '/yorumlar'
      fullPath: '/yorumlar'
      preLoaderRoute: typeof YorumlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fizyoterapist': {
      id: '/fizyoterapist'
      path: '/fizyoterapist'
      fullPath: '/fizyoterapist'
      preLoaderRoute: typeof FizyoterapistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egitmenlerimiz': {
      id: '/egitmenlerimiz'
      path: '/egitmenlerimiz'
      fullPath: '/egitmenlerimiz'
      preLoaderRoute: typeof EgitmenlerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  EgitmenlerimizRoute: EgitmenlerimizRoute,
  FizyoterapistRoute: FizyoterapistRoute,
  GaleriRoute: GaleriRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  YorumlarRoute: YorumlarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
